### ISSUE TITLE
fuint-db.sql 需要更新一下， 代码里面好多逻辑此sql建表中都没建表

### ISSUE THREAD

**Issue by wangshoujunnew** [fushengqian/fuint#49]
例如： ### SQL: select * from mt_message t where t.TYPE = ? and t.IS_SEND = 'N' order by t.SEND_TIME asc
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 't.IS_SEND' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 't.IS_SEND' in 'where clause'

**Comment by fushengqian** [comment]
好的
