### ISSUE TITLE
用了阿里镜像 jdk1.8 依旧报com.github.wxpay.sdk不存在

### ISSUE THREAD

**Issue by 496700939** [fushengqian/fuint#52]
<dependency>
    <groupId>com.github.wxpay</groupId>
    <artifactId>wxpay-sdk</artifactId>
    <version>0.0.3</version>
</dependency>

是这个版本吗

**Comment by fushengqian** [comment]
设置里确认jdk版本，这是网络上的包，不可能不存在的
![image](https://github.com/fushengqian/fuint/assets/1332589/211b6d46-c4dc-4feb-8da3-3e8dcc0f9e32)
